version: '3.8'

networks:
  admin-microservice-network:
    driver: bridge

services:
  go-api:
    container_name: admin-microservice-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:${PORT}
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs/
    networks:
      - admin-microservice-network

  postgres:
    image: postgres:16
    container_name: admin-microservice-postgres-db
    restart: always
    ports:
      - 5432:${DB_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - admin-microservice-network
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis
    container_name: admin-microservice-redis-db
    restart: always
    ports:
      - 6379:${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - admin-microservice-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres:
    name: admin-microservice-db
    driver: local
